### ISSUE TITLE
Trigger záznamu

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/RSMS02#3]
Pro záznam dat je potřeba trigger, který spustí záznam při výskytu blesku.  Zatím byly testovány tyto triggerovací techniky: 

1. Ruční spouštění zmáčknutím tlačítka (Trpí výběrovým efektem, kdy jsou zaznamenávány jen viditelné a silné blesky)
2. Triggerování od šířky pulzu (Při špatném nastavení generovat poměrně velké množství falešných záznamů)
3. Generování triggeru pomocí modulu [LIGHTNING01A](https://www.mlab.cz/module/LIGHTNING01A) - Moc se neosvědčilo zejména kvůli malé citlivosti a množství generovaných falešných triggerů v některých bouřkách. 

Jako nejlepší tak zřejmě vychází první dvě techniky, které je vhodné i kombinovat. Jde o algoritmické triggerování z amplitudy a šířky pulzu  a triggerovací tlačítko, které ovládá obsluha měřícího vozu. 

## Implementace algoritmu

Při algoritmické implementaci, je důležité, aby bylo možné triggerovat od události vzniklé na libovolném z kanálů. Neboť dopředu nevíme který radiový kanál detekuje výskyt blesku. Trigger by tak vytvořil kanál, který dříve splní podmínky. 

Na osciloskopu bylo vyzkoušeno, že dostatečně dobře funguje triggerování od úrovně signálu a šířky pulzu. (Minimální doby po kterou zůstává signál nad prahovou hodnotou). Reálně se používá tento rozsah parametrů 

-  Level 10 až 60 mV
-  Délka 5 až 20 us

**Rozsah parametrů by bylo potřeba mít nastavitelný buď skriptem, nebo konfiguračním souborem.** 

Pro implementaci triggerovacího algoritmu existují dva možné přístupy: 

- Algoritmus implementovat v GNUradiu, nebo případně jej doplnit do některého z jeho bloků
- Algoritmus implementovat v FPGA. 

Pro obě řešení je důležité že [experimentem se ukázalo](https://github.com/UniversalScientificTechnologies/RSMS02/issues/2), že zřejmě není nutná vyšší vzorkovací frekvence než 2.5MHz.  Triggerování tak může být implementováno na kontinuálním toku dat přenášeném přes 1G ethernet.
Problémem zde však je, jak zajistit přesnou časovou informaci o výskytu triggeru, respektive o přesném časovém umístění jednotlivých vzorků. Neboť časové zpoždění dat přenášených přes ethernet je neznámé.

V GNUradiu je momentálně implementováno klasické triggerování od úrovně signálu. Jiný způsob triggerování by zřejmě bylo nutné doplnit.  

Zároveň zde vzniká komplikace v tom, že ve stejnou chvíli je nutné spustit záznam z více přístrojů.  Algoritmický trigger, by tak potřeboval nějaký poměrně rychlý sekundární výstup. Asi je akceptovatelné, aby byl realizován i přes ethernet. Neboť většina přístrojů je schopná realizovat záznam v jednotkách sekund, kde časové zpoždění v řádu desítek milisekund nehraje příliš roli. 
Je však potřeba zajistit, aby ostatní přístroje (pokud nebudou čas odměřovat od v čase přesně lokalizovaného triggeru). Měly svojí přesnou lokalizaci dat v čase. To je nyní problém zejména u kamery.

Všechny přístroje ale kromě ovládaní přes ethernet mají ještě TTL vstup pro spouštění záznamu. Znamená to ovšem po autě (včetně střechy) rozvést koaxiální kabel obsahující signál triggeru. 

Zařízení, která musí být na základě triggeru spouštěna: 

- [vysokorychlostní kamera](https://github.com/ODZ-UJF-AV-CR/CRREAT_cars/tree/master/chronos_camera)
- [Parallella s QFH anténami](https://github.com/UniversalScientificTechnologies/RSMS01)
- Případně další přístroje jako např osciloskop nebo detektor ionizujícího záření, které mají většinou TTL vstup pro trigger

## Implementace tlačítka

Triggerovací tlačítko by zřejmě bylo vhodné použít technicky stejné, jako [pro vypouštěcí platformu vírníku](https://github.com/ThunderFly-aerospace/TF-SIMPLEPLATFORM/issues/4).

Zde nevzniká problém se spouštěním dalších přístrojů, neboť jak kamera na střeše, tak i Parallella mají TTL vstup pro trigger.  Je zde pouze nutné uložit přesný časový záznam o vzniku triggeru například pomocí zařízení [TIMESTAMPBOX01](https://github.com/UniversalScientificTechnologies/TIMESTAMPBOX01).

Možná by bylo ale dobré TIMESTAMPBOX rozřířit ještě o MCU a vytvořit tak něco jako  ROS2 tlačíko. Byla by to prostě krabička s BNC a USB konektorem a MIC konektorem na připojení tlačítka.

**Comment by roman-dvorak** [comment]
> Nebo bude mezi auty probíhat nějaká komunikace a budou se ukládat blesky na základě detekce na více autech současně.

Jak přesně je potřeba mít tu synchronizační značku? Resp. stačí do cca 2s po události říct, že tahle událost byla detekovaná ve více autech?

**Comment by kaklik** [comment]
> > Nebo bude mezi auty probíhat nějaká komunikace a budou se ukládat blesky na základě detekce na více autech současně.
> 
> Jak přesně je potřeba mít tu synchronizační značku? Resp. stačí do cca 2s po události říct, že tahle událost byla detekovaná ve více autech?

2s jsou myslím už neakceptovatelně dlouho. Je to kvůli tomu, že většina zařízení má buffer třeba na sekundu zpátky. Tudíž si myslím že akceptovatelné spoždění jsou maximálně jednotky stovek milisekund.

**Comment by kaklik** [comment]
Aktuálně vyřešeno implementací detekce v FPGA. Výstupem detekce je binární signál, který zatáhne za globální trigger signál, který je fyzicky rozveden do druhé RSMS01 Parallelly a do rychlé all-sky kamery na střeše. 

Paralelně k algoritmickému triggeru je připojeno tlačítko umístěné na řadící páce. 

![image](https://user-images.githubusercontent.com/1194177/199113605-3e6237f8-8009-483c-a718-8569ef3a4be2.png)

Zařízení TIMESTAMPBOX bylo nahrazeno připojením GPS na seriovou linku Omnie v kufru auta. LXC kontejner v omnii pak čte a loguje časové značky pomocí skriptu [triggermarks.py](https://github.com/ODZ-UJF-AV-CR/CRREAT_cars/blob/master/gps/triggermarks.py).
